#
# Owen Kelley
# Quiz 1
#

# Question 1
SELECT BOOK.BOOK_SUBJECT, COUNT(BOOK.BOOK_SUBJECT) AS 'Books In Subject'
FROM BOOK
WHERE BOOK.BOOK_SUBJECT!= 'Middleware'
GROUP BY BOOK.BOOK_SUBJECT
ORDER BY COUNT(BOOK.BOOK_SUBJECT)DESC, BOOK.BOOK_SUBJECT;

# Question 2
SELECT CONCAT(PATRON.PAT_FNAME," ", PATRON.PAT_LNAME) AS 'Full Name'
FROM PATRON
JOIN CHECKOUT ON CHECKOUT.PAT_ID = PATRON.PAT_ID
WHERE CHECKOUT.CHECK_DUE_DATE < CHECKOUT.CHECK_IN_DATE
ORDER BY PATRON.PAT_LNAME;

# Question 3
SELECT UPPER(AUTHOR.AU_LNAME) AS "Author's Last Name", BOOK.BOOK_TITLE AS 'Book Title', CONCAT("$",BOOK.BOOK_COST) AS "Book Cost"
FROM AUTHOR
JOIN WRITES ON WRITES.AU_ID = AUTHOR.AU_ID
JOIN BOOK ON BOOK.BOOK_NUM = WRITES.BOOK_NUM
WHERE BOOK.BOOK_COST < 85 AND BOOK.BOOK_COST > 65
ORDER BY BOOK.BOOK_COST DESC, AUTHOR.AU_LNAME;


