
/*   OWEN KELLEY    */
/*  SQL Homework 2  */

##################################################################
#9
SELECT COUNT(INV_NUMBER) 
FROM INVOICE;

##################################################################
#10
SELECT COUNT(CUS_BALANCE) 
FROM CUSTOMER 
WHERE CUS_BALANCE>500;

##################################################################
#11
SELECT INVOICE.CUS_CODE, INVOICE.INV_NUMBER, INVOICE.INV_DATE, PRODUCT.P_DESCRIPT, LINE.LINE_UNITS, LINE.LINE_PRICE
FROM INVOICE
JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
JOIN PRODUCT ON LINE.P_CODE = PRODUCT.P_CODE
ORDER BY INVOICE.CUS_CODE;

##################################################################
#12
SELECT INVOICE.CUS_CODE, INVOICE.INV_NUMBER, PRODUCT.P_DESCRIPT, LINE.LINE_UNITS AS "Units Bought", LINE.LINE_PRICE AS "Unit Price", LINE_UNITS*LINE_PRICE AS "Subtotal"
FROM INVOICE
JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
JOIN PRODUCT ON LINE.P_CODE = PRODUCT.P_CODE
ORDER BY CUS_CODE, INV_NUMBER, P_DESCRIPT;

##################################################################
#13
SELECT CUSTOMER.CUS_CODE, CUSTOMER.CUS_BALANCE, SUM(LINE.LINE_UNITS*LINE.LINE_PRICE) AS "Total Purchases"
FROM CUSTOMER
JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
JOIN LINE ON LINE.INV_NUMBER = INVOICE.INV_NUMBER
GROUP BY CUS_CODE;

##################################################################
#14
SELECT CUSTOMER.CUS_CODE, CUSTOMER.CUS_BALANCE, SUM(LINE.LINE_UNITS*LINE.LINE_PRICE) AS "Total Purchases", COUNT(LINE.INV_NUMBER) AS "Number of Purchases"
FROM CUSTOMER
JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
JOIN LINE ON LINE.INV_NUMBER = INVOICE.INV_NUMBER
GROUP BY CUS_CODE;

##################################################################
#15
SELECT CUSTOMER.CUS_CODE, CUSTOMER.CUS_BALANCE, 
SUM(LINE.LINE_UNITS*LINE.LINE_PRICE) AS "Total Purchases", 
COUNT(LINE.INV_NUMBER) AS "Number of Purchases", SUM(LINE.LINE_UNITS*LINE.LINE_PRICE)/COUNT(LINE.INV_NUMBER) AS "Average Purchase Amount"
FROM CUSTOMER
JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
JOIN LINE ON LINE.INV_NUMBER = INVOICE.INV_NUMBER
GROUP BY CUS_CODE;
##################################################################
#16
SELECT LINE.INV_NUMBER, SUM(LINE.LINE_UNITS*LINE.LINE_PRICE) AS "Invoice Total"
FROM LINE
GROUP BY INV_NUMBER;
##################################################################
#17
SELECT CUSTOMER.CUS_CODE, LINE.INV_NUMBER, SUM(LINE.LINE_UNITS*LINE.LINE_PRICE) AS "Invoice Total"
FROM CUSTOMER
JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
JOIN LINE ON LINE.INV_NUMBER = INVOICE.INV_NUMBER
GROUP BY INV_NUMBER
ORDER BY CUS_CODE, INV_NUMBER;
##################################################################
#18
SELECT CUSTOMER.CUS_CODE, COUNT(INVOICE.CUS_CODE) AS "Number of Invoices", SUM(LINE.LINE_UNITS*LINE.LINE_PRICE) AS "Total Purchases"
FROM CUSTOMER
JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
JOIN LINE ON LINE.INV_NUMBER = INVOICE.INV_NUMBER
GROUP BY CUS_CODE
ORDER BY CUS_CODE;

#Gets the number of invoices correctly
#SELECT COUNT(INVOICE.CUS_CODE) FROM INVOICE GROUP BY CUS_CODE





