
# OWEN KELLEY

#67
SELECT CHECK_NUM, BOOK_NUM, CHECK_OUT_DATE
FROM CHECKOUT
WHERE CHECK_OUT_DATE < '2017-4-5';

#69
SELECT BOOK_NUM, BOOK_TITLE, BOOK_SUBJECT, BOOK_COST
FROM BOOK
WHERE (BOOK_SUBJECT = 'Cloud' OR BOOK_SUBJECT = 'Middleware') AND BOOK_COST > 70
ORDER BY BOOK_NUM;

#70
SELECT AU_ID, AU_FNAME, AU_LNAME, AU_BIRTHYEAR
FROM AUTHOR
WHERE AU_BIRTHYEAR >= 1980 AND AU_BIRTHYEAR <=1989;

#80
SELECT (COUNT(BOOK.BOOK_NUM) - COUNT(BOOK.PAT_ID)) AS 'AVAILABLE BOOKS'
FROM BOOK;

#85
SELECT AU_ID, COUNT(AU_ID)AS 'BOOKS WRITTEN'
FROM WRITES
GROUP BY AU_ID
ORDER BY COUNT(AU_ID), AU_ID;


#96
SELECT AUTHOR.AU_ID, AUTHOR.AU_FNAME, AUTHOR.AU_LNAME, BOOK.BOOK_NUM, BOOK.BOOK_TITLE
FROM AUTHOR
JOIN WRITES ON WRITES.AU_ID = AUTHOR.AU_ID
JOIN BOOK ON BOOK.BOOK_NUM = WRITES.BOOK_NUM
WHERE BOOK.BOOK_SUBJECT = 'Cloud'
ORDER BY BOOK_NUM, AU_LNAME;

#98
SELECT BOOK.BOOK_NUM, BOOK.BOOK_TITLE, COUNT(CHECKOUT.BOOK_NUM)
FROM BOOK
JOIN CHECKOUT ON CHECKOUT.BOOK_NUM = BOOK.BOOK_NUM
GROUP BY CHECKOUT.BOOK_NUM
ORDER BY COUNT(CHECKOUT.BOOK_NUM)DESC;

#100
SELECT AUTHOR.AU_ID, AUTHOR.AU_LNAME, BOOK.BOOK_TITLE, CHECK_OUT_DATE, PAT_LNAME
FROM AUTHOR
JOIN WRITES ON WRITES.AU_ID = AUTHOR.AU_ID
JOIN BOOK ON BOOK.BOOK_NUM = WRITES.BOOK_NUM
JOIN PATRON ON PATRON.PAT_ID = BOOK.PAT_ID
JOIN CHECKOUT ON CHECKOUT.BOOK_NUM = BOOK.BOOK_NUM
WHERE AUTHOR.AU_LNAME = 'Bruer' AND PATRON.PAT_LNAME = 'Miles'
ORDER BY CHECKOUT.CHECK_OUT_DATE;

#101
SELECT PATRON.PAT_ID, PATRON.PAT_FNAME, PATRON.PAT_LNAME
FROM PATRON
WHERE PAT_ID NOT IN (SELECT PAT_ID FROM CHECKOUT);

#105
SELECT BOOK_NUM, BOOK_TITLE, BOOK_COST
FROM BOOK
WHERE BOOK_COST = (SELECT MIN(BOOK_COST) FROM BOOK);

#106
SELECT AUTHOR.AU_ID, AUTHOR.AU_FNAME, AUTHOR.AU_LNAME
FROM AUTHOR
JOIN WRITES ON WRITES.AU_ID = AUTHOR.AU_ID
JOIN BOOK ON BOOK.BOOK_NUM = WRITES.BOOK_NUM
WHERE BOOK_SUBJECT != 'Programming'
ORDER BY AUTHOR.AU_LNAME;

#108
SELECT BOOK.BOOK_NUM, BOOK.BOOK_TITLE, BOOK.BOOK_SUBJECT, AUTHOR.AU_LNAME, COUNT(BOOK.BOOK_NUM)
FROM BOOK
JOIN WRITES ON WRITES.BOOK_NUM = BOOK.BOOK_NUM
JOIN AUTHOR ON AUTHOR.AU_ID = WRITES.AU_ID
WHERE BOOK.BOOK_SUBJECT = 'Cloud'
GROUP BY BOOK.BOOK_TITLE
ORDER BY BOOK.BOOK_TITLE, AUTHOR.AU_LNAME;



